# Generated by Django 5.1.15 on 2026-02-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('l', 'L'), ('unit', 'unité'), ('bunch', 'botte')], default='unit', max_length=20)),
                ('quantity_in_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alert_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('storage_location', models.CharField(blank=True, max_length=120)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
