# Generated by Django 5.1.15 on 2026-02-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('day', 'Jour'), ('week', 'Semaine'), ('month', 'Mois'), ('year', 'Année')], default='day', max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
