# Generated by Django 5.1.15 on 2026-02-20 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderstatuslog"),
        ("orders", "0003_order_notification"),
    ]

    operations = []
