# Generated by Django 5.1.15 on 2026-02-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_merge_0002_orderstatuslog_0003_order_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("EN_ATTENTE", "En attente"),
                    ("PREPARATION", "En préparation"),
                    ("PRETE", "Prête"),
                    ("SERVIE", "Servie"),
                    ("EN_ROUTE", "En route"),
                    ("LIVREE", "Livrée"),
                    ("PAYEE", "Payée"),
                    ("ANNULEE", "Annulée"),
                ],
                default="EN_ATTENTE",
                max_length=20,
            ),
        ),
    ]
